version: "3"

services:
  application:
    build: .
    command: >
      sh -c "python manage.py makemigrations
             python manage.py migrate
             python runserver 0.0.0.0:8000" 
    env_file:
      - ./.env
    volumes:
      - ./server:/server

  redis:
    image: redis:alpine
  
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - ./server:/server
    env_file:
      - ./.env
    depends_on:
      - redis
      - application