# Generated by Django 4.2.2 on 2023-06-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Очки английского'),
        ),
    ]
