# Generated by Django 4.2.2 on 2023-07-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/avatars/', verbose_name='Avatar')),
                ('level', models.CharField(blank=True, default='A1', max_length=100, verbose_name='Уровень английского')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Очки английского')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
