# Generated by Django 4.2.2 on 2023-07-01 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='users.account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('time_send', models.DateTimeField(auto_now=True, verbose_name='Время сообщения')),
                ('type', models.CharField(choices=[('remark', 'Remark'), ('pupil', 'Pupil')], default='remark', max_length=100, verbose_name='Тип сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chats.chat')),
                ('reply_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
